name: ChatListener
version: 1.1
main: ChatListener
api-version: 1.12
commands:
  bot:
    description: Comando principal para interactuar con diferentes bots.
    usage: /bot <nombre_de_bot>
    subcommands:
      insultbot:
        description: Lanza un insulto aleatorio.
        usage: /bot insultbot
      tntbot:
        description: Lanza bloques de TNT sobre el jugador.
        usage: /bot tntbot
      infobot:
        description: Muestra información sobre los diferentes bots.
        usage: /bot infobot
